# Use Java 21
FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app
COPY ../backend/pom.xml .
COPY ../backend/src ./src
RUN ./mvnw clean package -DskipTests
EXPOSE 8080
CMD ["java", "-jar", "target/backend-0.0.1-SNAPSHOT.jar"]
